### PR TITLE
Bugfix: missing attribute definition

### LINKED ISSUE #48: Definition is not set on object attribute
**Describe the bug**

When we use the aws metadata with this tf: 
```tf
resource "aws_elb" "aws_elb_620fea2f" {
  listener {
    lb_port = 404
    value = "test"
  }
  test {
    value = 1
  }
}
```

The attributes `listener`  and `lb_port` don't have definition even if its exists in the metadata.

### PR DESCRIPTION
**Pull request by Zorin95670**
Resolved #48

### CODE REVIEW

**Review by justinehell — DISMISSED** [review]

File: src/parser/TerraformListener.js [hunk 1]
```diff
@@ -209,24 +213,35 @@ class TerraformListener extends antlr4.tree.ParseTreeListener {
         .push(this.currentField);
     }
 
-    if (this.currentComponent.definition) {
-      this.currentField.definition = this.currentComponent.definition.definedAttributes
-        .find((definitionAttribute) => definitionAttribute.name === this.currentField.name)
-        || null;
+    let definition;
```
Comment (k-y0u) [inline src/parser/TerraformListener.js:216]: why do you use a variable ?

File: src/parser/TerraformListener.js [hunk 2]
```diff
@@ -209,24 +213,35 @@ class TerraformListener extends antlr4.tree.ParseTreeListener {
...
+
+    if (this.currentComplexeField) {
+      definition = this.getAttributeDefinition(this.currentComplexeField, this.currentField.name);
+    } else {
+      definition = this.getAttributeDefinition(this.currentComponent, this.currentField.name);
     }
+
+    this.currentField.definition = definition;
```
Comment (k-y0u) [inline src/parser/TerraformListener.js:224]: why do that just before
`this.currentField = null;`

**Review by k-y0u — CHANGES_REQUESTED** [review]

**Review by k-y0u — APPROVED** [review]
